### ISSUE TITLE
ExceptionInInitializerError while injecting JcromCrudProvider in a WisdomTest

### ISSUE THREAD

**Issue by agonist** [wisdom-framework/wisdom-jcr#5]
I have a ExceptionInInitializerError when I try to inject a [JcromCurdProvider](https://github.com/wisdom-framework/wisdom-jcr/blob/master/wisdom-jcr-core/src/main/java/org/wisdom/jcrom/runtime/JcromCrudProvider.java) in a [WisdomTest](https://github.com/wisdom-framework/wisdom-jcr/blob/master/jcr-test/src/test/java/org/wisdom/jcrom/multipackage/MultiPackageIT.java) .

Any idea of why I get this error? since I have no issue outside tests

Stacktrace :  

```
java.lang.ExceptionInInitializerError: Cannot inject a service in jcromCrudProvider, cannot find a service publishing org.wisdom.jcrom.runtime.JcromCrudProvider matching the filter null
    at org.wisdom.test.parents.DependencyInjector.inject(DependencyInjector.java:146)
    at org.wisdom.test.parents.DependencyInjector.inject(DependencyInjector.java:66)
    at org.wisdom.test.shared.InVivoRunner.createTest(InVivoRunner.java:58)
    at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.wisdom.test.shared.InVivoRunner.run(InVivoRunner.java:64)
    at org.wisdom.test.WisdomRunner.run(WisdomRunner.java:78)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by cescoffier** [comment]
Does it work on your machine or not at all. I saw the error on the CI.

**Comment by agonist** [comment]
not at all. But I don't understand why

**Comment by cescoffier** [comment]
Ok, will have a look.

**Comment by cescoffier** [comment]
Fixed

The `@Inject` field was not a service. So it was not able to find it. I use the `OSGiHelper` to retrieve the `Crud` services.

I also change how you load the `packages` entry using the HOCON list support.

**Comment by agonist** [comment]
Cool thank's for the help !
