### ISSUE TITLE
Error : JCR Modeshape Sample doesn't work 

### ISSUE THREAD

**Issue by Atiras** [wisdom-framework/wisdom-jcr#9]
When I try to run the sample, i have this error : 

```
[ERROR]  : [todo.controllers.TodoController-0] The callback method start has thrown an exception : The absPath argument may not be null 
java.lang.IllegalArgumentException: The absPath argument may not be null
    at org.modeshape.common.util.CheckArg.isNotNull(CheckArg.java:391) ~[modeshape-common-4.2.0.Final.jar:4.2.0.Final]
    at org.modeshape.common.util.CheckArg.isNotZeroLength(CheckArg.java:358) ~[modeshape-common-4.2.0.Final.jar:4.2.0.Final]
    at org.modeshape.common.util.CheckArg.isNotEmpty(CheckArg.java:373) ~[modeshape-common-4.2.0.Final.jar:4.2.0.Final]
    at org.modeshape.jcr.JcrSession.nodeExists(JcrSession.java:946) ~[modeshape-jcr-4.2.0.Final.jar:4.2.0.Final]
    at org.wisdom.jcrom.runtime.JcrCrudService.checkPath(JcrCrudService.java:130) ~[org.wisdom.framework.jcr.wisdom.jcr.core-1.0-SNAPSHOT.jar:na]
    at org.wisdom.jcrom.runtime.JcrCrudService.save(JcrCrudService.java:116) ~[org.wisdom.framework.jcr.wisdom.jcr.core-1.0-SNAPSHOT.jar:na]
    at org.wisdom.api.model.Crud$$Proxy.save(Unknown Source) ~[na:na]
    at todo.controllers.TodoController.__M_start(TodoController.java:66) ~[na:na]
    at todo.controllers.TodoController.start(TodoController.java) ~[na:na]
```

**Comment by amischler** [comment]
Thanks for pointing this out. Fixed in latest 1.0-SNAPSHOT.
